---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: kibana
server.host: ${NETWORK_HOST}
elasticsearch.hosts: [ "${ELASTIC_URL}:${ELASTIC_PORT}" ]
monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
#
elasticsearch.username: ${ELASTIC_USER}
elasticsearch.password: ${ELASTIC_PASSWORD}
